-- ===========================================================================
-- CarRental — schema + seed data
--
-- Paste this whole file into the Supabase SQL Editor and press Run.
-- It creates the three tables and loads every row from
-- my-react-app/src/data/mockCars.js.
--
-- !! WARNING !!
-- Section 1 DROPS the tables first so the script can be re-run cleanly.
-- On a fresh project that is harmless. If you already have real data,
-- comment out Section 1 before running.
--
-- RLS is deliberately NOT enabled here — that is a separate step. Until you
-- enable it, anyone with your anon key can read and write these tables, so
-- do not treat this as production-ready.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. Reset (comment this section out if you have data you want to keep)
-- ---------------------------------------------------------------------------
drop table if exists bookings cascade;
drop table if exists cars cascade;
drop table if exists car_categories cascade;


-- ---------------------------------------------------------------------------
-- 2. Tables
-- ---------------------------------------------------------------------------

create table car_categories (
  id   integer generated by default as identity primary key,
  name text not null unique
);

create table cars (
  id           bigint generated by default as identity primary key,
  category_id  integer not null references car_categories (id),
  make         text    not null,
  model        text    not null,
  year         integer not null check (year between 1980 and 2100),
  color        text    not null,
  seats        integer not null check (seats > 0),

  -- NOTE: 'AutoManual' is only here because car id 2 in the mock data uses it.
  -- Our documented contract is 'automatic' | 'manual'. Once that row is fixed,
  -- tighten this with:
  --   alter table cars drop constraint cars_transmission_check;
  --   alter table cars add constraint cars_transmission_check
  --     check (transmission in ('automatic','manual'));
  transmission text not null
               check (transmission in ('automatic', 'manual', 'AutoManual')),

  mileage      integer not null default 0 check (mileage >= 0),
  daily_rate   numeric(10,2) not null check (daily_rate > 0),
  image_url    text,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now()
);

create index cars_category_id_idx on cars (category_id);
create index cars_is_active_idx   on cars (is_active);

create table bookings (
  id          bigint generated by default as identity primary key,

  -- Nullable for now: the seed bookings predate auth, so they have no owner.
  -- After auth is wired up and every row has a user, make it required:
  --   alter table bookings alter column user_id set not null;
  user_id     uuid references auth.users (id) on delete cascade,

  car_id      bigint not null references cars (id),
  pickup_at   date    not null,
  return_at   date    not null,
  status      text    not null default 'pending'
              check (status in ('pending','confirmed','active','returned','cancelled')),
  total_price numeric(10,2) not null check (total_price >= 0),
  created_at  timestamptz not null default now(),

  constraint bookings_dates_ordered check (return_at > pickup_at)
);

create index bookings_car_id_idx  on bookings (car_id);
create index bookings_user_id_idx on bookings (user_id);


-- ---------------------------------------------------------------------------
-- 3. Categories (6 rows)
-- ---------------------------------------------------------------------------
insert into car_categories (id, name) values
  (1, 'Economy'),
  (2, 'Sedan'),
  (3, 'SUV'),
  (4, 'Luxury'),
  (5, 'Van'),
  (6, 'DaBaby')
on conflict (id) do nothing;


-- ---------------------------------------------------------------------------
-- 4. Cars (12 rows)
-- ---------------------------------------------------------------------------
insert into cars
  (id, category_id, make, model, year, color, seats, transmission, mileage,
   daily_rate, image_url, is_active)
values
  (1,  1, 'Toyota',        'Corolla',        2023, 'Silver', 5, 'automatic',  18420,  42.00,
      'https://placehold.co/600x400?text=Toyota+Corolla', true),
  (2,  6, 'DaBaby',        'Mobile',         2019, 'Brown',  1, 'AutoManual', 31780, 500.00,
      'https://lede-admin.dailydot.com/wp-content/uploads/sites/69/2024/07/dababy-convertible.jpg', true),
  (3,  1, 'Kia',           'Rio',            2021, 'Blue',   5, 'manual',     47310,  38.00,
      'https://placehold.co/600x400?text=Kia+Rio', false),
  (4,  2, 'Toyota',        'Camry',          2024, 'Black',  5, 'automatic',   9120,  58.00,
      'https://placehold.co/600x400?text=Toyota+Camry', true),
  (5,  2, 'Honda',         'Accord',         2023, 'Gray',   5, 'automatic',  22650,  62.00,
      'https://placehold.co/600x400?text=Honda+Accord', true),
  (6,  3, 'Jeep',          'Grand Cherokee', 2023, 'Green',  5, 'automatic',  27400,  89.00,
      'https://placehold.co/600x400?text=Jeep+Grand+Cherokee', true),
  (7,  3, 'Subaru',        'Outback',        2022, 'White',  5, 'automatic',  38990,  76.00,
      'https://placehold.co/600x400?text=Subaru+Outback', true),
  (8,  3, 'Ford',          'Explorer',       2024, 'Black',  7, 'automatic',  12030,  95.00,
      'https://placehold.co/600x400?text=Ford+Explorer', true),
  (9,  4, 'BMW',           '5 Series',       2024, 'Black',  5, 'automatic',   6480, 165.00,
      'https://placehold.co/600x400?text=BMW+5+Series', true),
  (10, 4, 'Porsche',       'Macan',          2023, 'White',  5, 'automatic',  11250, 250.00,
      'https://placehold.co/600x400?text=Porsche+Macan', true),
  (11, 5, 'Chrysler',      'Pacifica',       2023, 'Silver', 7, 'automatic',  34870, 105.00,
      'https://placehold.co/600x400?text=Chrysler+Pacifica', true),
  (12, 5, 'Mercedes-Benz', 'Sprinter',       2022, 'White', 12, 'manual',     56200, 140.00,
      'https://placehold.co/600x400?text=Mercedes+Sprinter', true)
on conflict (id) do nothing;


-- ---------------------------------------------------------------------------
-- 5. Bookings (3 rows)
--
-- total_price values are already consistent with days x daily_rate:
--   Camry    4 days x  58 = 232
--   BMW      3 days x 165 = 495
--   Corolla  4 days x  42 = 168
-- ---------------------------------------------------------------------------
insert into bookings
  (id, user_id, car_id, pickup_at, return_at, status, total_price)
values
  (1, null, 4, '2026-10-04', '2026-10-08', 'confirmed', 232.00),
  (2, null, 9, '2026-10-18', '2026-10-21', 'pending',   495.00),
  (3, null, 1, '2026-09-12', '2026-09-16', 'returned',  168.00)
on conflict (id) do nothing;


-- ---------------------------------------------------------------------------
-- 6. Resync the identity sequences
--
-- REQUIRED. We inserted explicit ids, so the sequences still start at 1 and
-- the next natural insert would collide with an existing row. This pushes
-- each sequence past the highest id currently in the table.
-- ---------------------------------------------------------------------------
select setval(pg_get_serial_sequence('car_categories', 'id'),
              coalesce((select max(id) from car_categories), 1));
select setval(pg_get_serial_sequence('cars', 'id'),
              coalesce((select max(id) from cars), 1));
select setval(pg_get_serial_sequence('bookings', 'id'),
              coalesce((select max(id) from bookings), 1));


-- ---------------------------------------------------------------------------
-- 7. Prevent double-booking at the database level
--
-- Two users can both pass an availability check and then both insert. No
-- amount of application code fixes that race — the database has to reject it.
-- This makes overlapping live bookings for the same car impossible.
--
-- The '[)' bound means a booking ending the same day another starts is
-- allowed, which is what we want.
-- ---------------------------------------------------------------------------
create extension if not exists btree_gist;

alter table bookings add constraint bookings_no_overlap
  exclude using gist (
    car_id WITH =,
    daterange(pickup_at, return_at, '[)') WITH &&
  ) where (status in ('pending', 'confirmed', 'active'));


-- ---------------------------------------------------------------------------
-- 8. Verify — these should return 6, 12, 3
-- ---------------------------------------------------------------------------
select 'categories' as table_name, count(*) from car_categories
union all
select 'cars',       count(*) from cars
union all
select 'bookings',   count(*) from bookings;
